<div class="moduletablelogin">
	<?php if($connectedUser): ?>
		<div class="connecteduser">		
		    <div class="floatleft">
		        <img alt="Profile Pic" src="<?php echo $this->basepath(); ?>/img/img-profile.png">
		    </div>
		    <div class="floatleft">
		        <ul class="floatleft">
		            <li>
		            	Bienvenue <?php echo $this->escapehtml($connectedUser->nom . ' ' . $connectedUser->prenom); ?><br>

		            	<span class="small grey"><?php echo $this->labeltypeuser_helper($connectedUser->type); ?></span>
		            	<br>
		            	
		            	<span class="small grey">
		            		<?php echo $this->escapehtml(($this->labeletablissement_helper($connectedUser->et_code_fk))); ?>
		            	</span>
		            	<br>
		            	
		            	<span class="small grey">
		            		<?php echo $this->escapehtml(($this->labelpui_helper($connectedUser->pui_code_fk))); ?>
		            	</span>
		            	<br>
		            </li>
		            <li><a href="<?php echo $this->basepath(); ?>/utilisateur/utilisateur/edit/<?php echo $connectedUser->user_code_pk; ?>">Mon Profil</a></li>
		            <li><a href="<?php echo $this->basepath(); ?>/utilisateur/utilisateur/logout">
						  Déconnexion</a>
					</li>
		        </ul>
		    </div>
		</div>
	<?php else: ?>
		  <a href='<?php echo $this->basepath(); ?>/utilisateur/utilisateur/login'>Connexion</a>
	<?php endif; ?>
</div>


<div>
	<table>
		<tr>
			<td>
				<a title="Accueil" href="<?php  echo $this->basepath(); ?>">
					<img width="150px" src="<?php  echo $this->basepath();?>/img/feedbacklogo.jpg" title="Logo" alt="" /></a>
			</td>
			<td><span class="title">Indicateurs</span></td>
		</tr>
	</table>
</div>

