<script src="<?php echo $this->basepath(); ?>/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
<style type="text/css" title="currentStyle">
	@import "<?= $this->basepath() ?>/css/dataTables.css";
</style>

<?php echo $this->titrepage_helper('Liste des magasins');  ?>


<div class="center-block" style="width:96%;">
	<p class="alert bg-success">
		<?php echo count($tabEtabs); ?> magasin(s) trouvé(s)
	</p>

	<table class="table table-striped table-bordered table-hover standard_table" id="table_etabs">
		<thead>
			<tr>
				<th>Nom</th>
				<th>Adresse</th>
				<th>Ville/CP/Pays</th>
				<th>NB&nbsp;lits</th>
				<th>Crée&nbsp;le</th>
				<th>Catégorie</th>
				<th>Statut</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($tabEtabs as $etabs): ?>
				<tr>
					<td><?php echo $this->escapehtml($etabs->getEtLibelle()); ?></td>
					<td><?php echo $this->escapehtml($etabs->getEtRue()); ?></td>
					<td>
						<?php echo $this->escapehtml($etabs->getEtVille()); ?>&nbsp;
						(<?php echo $this->escapehtml($etabs->getEtCp()); ?>)<br>
						<?php echo $this->escapehtml($etabs->getEtPays()); ?>
					</td>
					<td><?php echo $this->escapehtml($etabs->getEtNbLits()); ?></td>
					<td><?php echo $etabs->getEtCreation()->format('m/d/Y'); ?></td>
					<td><?php echo $this->escapehtml($etabs->getCaCodeFk()->getLibelle()); ?></td>
					<td><?php echo $this->escapehtml($etabs->getEtStatut()->getLibelle()); ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	
	</table>
</div>


<script language="javascript">
	$(document).ready(function() {
		$('#table_etabs').dataTable({
			"aaSorting": [],
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25,
	        "oLanguage": {
	            "sLengthMenu": "Afficher _MENU_ lignes par page",
	            "sZeroRecords": "Aucun magasin trouvé",
	            "sInfo": "Affiche _START_ à _END_ de _TOTAL_ magasin(s)",
	            "sInfoEmpty": "Aucun utilisateur trouvé",
	            "sInfoFiltered": "<br/>(Filtré à partir d'un total de _MAX_ magasin(s)",
	            "sSearch" : "<b>Affiner la recherche</b>",
		        "oPaginate": {
		            "sNext" : "Suivant",
					"sPrevious" : "Précédent",
					"sFirst" : "Premier",
					"sLast" : "Dernier",
		        }
	        },
	    });
	});
</script>

