<script src="<?php echo $this->basepath(); ?>/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
<style type="text/css" title="currentStyle">
	@import "<?= $this->basepath() ?>/css/.dataTables.css";
</style>


<?php 
	echo $this->titrepage_helper(
		'Liste des PUI', 
		(($etab) ? ('Etablissement : ' . $this->escapehtml($etab->getEtLibelle())) : '')
	); 
?>

<div class="center-block" style="width:80%;">
	<p class="alert bg-success">
		<?php echo count($tabPui); ?> PUI trouvée(s)
		
		<?php if($connectedUser->type == 2): ?>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<input type="button" value="Ajouter une PUI" class="btn btn-success"
				onClick="document.location='<?php echo $this->basepath(); ?>/etablissement/pui/add';">
		<?php endif; ?>
	</p>

	<table class="table table-striped table-bordered table-hover standard__table" id="table_pui">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nom</th>
				<th>Nombre de lits</th>
				<th>Etablissement</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($tabPui as $pui): ?>
				<tr>
					<td><?php echo $this->escapehtml($pui->getPuiCodePk()); ?></td>
					<td><?php echo $this->escapehtml($pui->getLibelle()); ?></td>
					<td><?php echo $this->escapehtml($pui->getNblits()); ?></td>
					<td><?php echo $this->escapehtml($pui->getEtabs()->getEtLibelle()); ?></td>
					<td>
						<a href="<?php echo $this->basepath() ?>/etablissement/pui/edit/<?php echo $pui->getPuiCodePk(); ?>" class="icon-edit" title="Editer">&nbsp;</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	
	</table>
</div>


<script language="javascript">
	$(document).ready(function() {
		$('#table_pui').dataTable({
			"aaSorting": [],
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25,
	        "oLanguage": {
	            "sLengthMenu": "Afficher _MENU_ lignes par page",
	            "sZeroRecords": "Aucune PUI trouvée",
	            "sInfo": "Affiche _START_ à _END_ de _TOTAL_ PUI(s)",
	            "sInfoEmpty": "Aucune PUI trouvée",
	            "sInfoFiltered": "<br/>(Filtré à partir d'un total de _MAX_ PUI(s)",
	            "sSearch" : "<b>Affiner la recherche</b>",
		        "oPaginate": {
		            "sNext" : "Suivant",
					"sPrevious" : "Précédent",
					"sFirst" : "Premier",
					"sLast" : "Dernier",
		        }
	        },
	    });
	});

</script>