<?php echo $this->titrepage_helper('Changement PUI'); ?>

<?php echo $this->alertmessages_helper($alertmessages); ?>

<?php if($user): ?>
	<div class="row">
		<div class="col-md-2"><strong>Etablissement actuel</strong></div>
		<div class="col-md-10"><?php echo $user->getEtabs()->getEtLibelle(); ?></div>
	</div>
	<div class="row">
		<div class="col-md-2"><strong>PUI actuelle</strong></div>
		<div class="col-md-10"><?php echo $user->getPui()->getLibelle(); ?></div>
	</div>
<?php endif; ?>

	<p>&nbsp;</p>

<?php if($invitation): ?>
	<div class="row">
		<div class="col-md-2"><strong>Nouvel magasin</strong></div>
		<div class="col-md-10"><?php echo $invitation->getEtabs()->getEtLibelle(); ?></div>
	</div>
	<div class="row">
		<div class="col-md-2"><strong>Nouvelle PUI</strong></div>
		<div class="col-md-10"><?php echo $invitation->getPui()->getLibelle(); ?></div>
	</div>
<?php endif; ?>
	
	<p>&nbsp;</p>
	
<?php if($form): ?>
	<form method="post">
		<input type="hidden" name="validation" value="1">
		<div class="row">
			<div class="col-md-2">&nbsp;</div>
			<div class="col-md-10"><input type="submit" value="Valider changement de la PUI" class="btn btn-success"></div>
		</div>
	</form> 
<?php endif; ?>
