<?php
	echo $this->titrepage_helper('Invitation utilisateur', null, $this->basepath() . '/utilisateur/utilisateur/list'); 
?>

<?php echo $this->alertmessages_helper($alertmessages); ?>

<?php if($form): ?>
	<?php echo $this->form()->openTag($form); ?>
	
		<p><?php echo $this->formRow($form->get('mail')); ?></p>
		<p><?php echo $this->formRow($form->get('pui')); ?></p>
		<p><?php echo $this->formRow($form->get('profil')); ?></p>
		
		<p><?php echo $this->formSubmit($form->get('submit')); ?></p>
	
	<?php echo $this->form()->closeTag(); ?>
<?php endif; ?>
