<script src="<?php echo $this->basepath(); ?>/bower_components/DataTables/media/js/jquery.dataTables.min.js"></script>
<style type="text/css" title="currentStyle">
	@import "<?= $this->basepath() ?>/css/.dataTables.css";
</style>

<?php echo $this->titrepage_helper('Liste des utilisateur', $complementTitre); ?>



<div class="center-block" style="width:96%;">
	<p class="alert bg-success">
		<?php echo count($tabUsers); ?> utilisateur(s) trouvé(s)
		
		<?php if($connectedUser->type == 2 || $connectedUser->type == 3): ?>
			&nbsp;&nbsp;&nbsp;&nbsp;
			<input type="button" value="Inviter un utilisateur" class="btn btn-success"
				onClick="document.location='<?php echo $this->basepath(); ?>/utilisateur/utilisateur/invitation';">
		<?php endif; ?>
	</p>

	<table class="table table-striped table-bordered table-hover standard__table" id="table_users">
		<thead>
			<tr>
				<th>Nom</th>
				<th>Préom</th>
				<th>Login</th>
				<th>Mail</th>
				<th>Crée le</th>
				<th>Statut</th>
				<th>Type</th>
				<?php if($affichageEtab): ?>
					<th>Etablissement</th>
				<?php endif; ?>
				<?php if($affichagePui): ?>
					<th>PUI</th>
				<?php endif; ?>
				<?php if($connectedUser->type == 2 || $connectedUser->type == 3): ?>
					<th>Actions</th>
				<?php endif; ?>
			</tr>
		</thead>
		<tbody>
			<?php foreach($tabUsers as $user): ?>
				<tr>
					<td><?php echo $this->escapehtml($user->getNom()); ?></td>
					<td><?php echo $this->escapehtml($user->getPrenom()); ?></td>
					<td><?php echo $this->escapehtml($user->getLogin()); ?></td>
					<td><?php echo $this->escapehtml($user->getEmail()); ?></td>
					<td><?php echo $user->getDateCreated()->format('m/d/Y'); ?></td>
					<td><?php echo $this->escapehtml($this->labelstatutuser_helper($user->getAcces())); ?></td>
					<td><?php echo $this->escapehtml($this->labeltypeuser_helper($user->getType())); ?></td>
					<?php if($affichageEtab): ?>
						<td><?php echo $this->escapehtml(($user->getEtabs()) ? $user->getEtabs()->getEtLibelle() : ''); ?></td>
					<?php endif; ?>
					<?php if($affichagePui): ?>
						<td><?php echo $this->escapehtml(($user->getPui()) ? $user->getPui()->getLibelle() : ''); ?></td>
					<?php endif; ?>
					<?php if($connectedUser->type == 2 || $connectedUser->type == 3): ?>
						<td>
								<a href="<?php echo $this->basepath() ?>/utilisateur/utilisateur/edit/<?php echo $user->getUserCodePk(); ?>" class="icon-edit" title="Editer">&nbsp;</a>
								<?php if($userpermission->canDeleteUser($user)): ?>
									<a href="javascript:;" class="icon-delete" title="Supprimer"
										onClick='deleteUser(<?php echo $user->getUserCodePk(); ?>, "<?php echo $user->getNom(); ?>", "<?php echo $user->getPrenom(); ?>");' >&nbsp;</a>
								<?php endif; ?>
								<?php if($userpermission->canChangeUserPui($user)): ?>
									<a href="<?php echo $this->basepath() ?>/utilisateur/utilisateur/invitation?mail=<?php echo $user->getEmail(); ?>" class="icon-invitation" title="Envoyer une invitation pour changer de PUI">&nbsp;</a>							
								<?php endif; ?>
								<a href="<?php echo $this->basepath() ?>/attribuer-indicateur/par-utilisateur/<?php echo $user->getUserCodePk(); ?>" class="icon-attribuer" title="Attribution des indicateurs">&nbsp;</a>
						</td>
					<?php endif; ?>
				</tr>
			<?php endforeach; ?>
		</tbody>
	
	</table>
</div>


<script language="javascript">
	$(document).ready(function() {
		$('#table_users').dataTable({
			"aaSorting": [],
			"sPaginationType": "full_numbers",
			"iDisplayLength": 25,
	        "oLanguage": {
	            "sLengthMenu": "Afficher _MENU_ lignes par page",
	            "sZeroRecords": "Aucun utilisateur trouvé",
	            "sInfo": "Affiche _START_ à _END_ de _TOTAL_ utilisateur(s)",
	            "sInfoEmpty": "Aucun utilisateur trouvé",
	            "sInfoFiltered": "<br/>(Filtré à partir d'un total de _MAX_ utilisateur(s)",
	            "sSearch" : "<b>Affiner la recherche</b>",
		        "oPaginate": {
		            "sNext" : "Suivant",
					"sPrevious" : "Précédent",
					"sFirst" : "Premier",
					"sLast" : "Dernier",
		        }
	        },
	    });
	});

	function deleteUser(id, nom, prenom)
	{
		var url = '<?php echo $this->basepath(); ?>/utilisateur/utilisateur/delete/' + id;
		if(confirm('Etes vous sûr de vouloir supprimer définitivement l\'utilisateur\n\n' + nom + ' ' + prenom + ' ?')) {
			document.location = url;
		}
	}

</script>

