<?php echo $this->doctype(); ?>
<?php @$connectedUser = $this->getauthentification_helper(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Indicateur')->setSeparator(" - ");//->append("easy ?!"); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '../img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        /* Theme style */
                        ->prependStylesheet($this->basePath() . '/bower_components/admin-lte/css/AdminLTE.css')
                        /* font Awesome */
                        ->prependStylesheet($this->basePath() . '/bower_components/admin-lte/css/font-awesome.min.css')
                        /* Ionicons */
                        ->prependStylesheet($this->basePath() . '/bower_components/admin-lte/css/ionicons.min.css')
                        ->prependStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css')
        ?>

        <?php echo $this->headScript()->prependFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js') ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

    </head>
    <body class="skin-blue layout-top-nav">
		<div id="main">
			<div class="ground" id="wrapper">

                <div id="header">
                    <?php include __DIR__ . '/common/header.phtml'; ?>
                </div>

                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#"></a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <?php include __DIR__ . '/menu/menu.phtml';?>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>

				<div id="main-content">
					<div class="container">
						<?php echo $this->content; ?>
					</div>
				</div>

                <div id="footer">
                    <?php include __DIR__ . '/common/footer.phtml'; ?>
                </div>

			</div>
		</div>
        
    </body>
</html>