<!-- Content Header (Page header) -->
<?php echo $this->titrepage_helper('Attribuer indicateurs', 'Attribution par indicateur');  ?>

<!-- Main content -->
<section class="content" ng-app="attribUsers" ng-controller="mainApp">
    <div class="container-fluid" ng-init='indicId=<?php echo $this->indicId; ?>'></div>
    <h2><?php echo $indic->getTitre() ?><small><?php echo $indic->getTache() ?></small></h2>

    <table-box data="test">
        <table-users data="test" indicid="indicId"></table-users>
    </table-box>
</section><!-- /.content -->

<script src="../../bower_components/angular/angular.js" type="text/javascript"></script>
<script src="../../bower_components/angular-route/angular-route.js"></script>
<script src="../../bower_components/angular-resource/angular-resource.js"></script>
<script src="../../bower_components/angular-animate/angular-animate.js"></script>
<!-- <script type="text/javascript" src="../bower_components/angular-growl-notifications/dist/angular-growl-notifications.js"></script>--><!--<script src="<?php $this->basePath(); ?>/bower_components/angular-bootstrap/ui-bootstrap.js" type="text/javascript"></script>-->
<script src="../../js/app.js" type="text/javascript"></script>
<script src="../../js/directives/tableBox.js" type="text/javascript"></script>
<script src="../../js/directives/usersTable.js" type="text/javascript"></script>
<script src="../../js/services/UsersByIndic.js" type="text/javascript"></script>
<script src="../../js/services/IndicsUsers.js" type="text/javascript"></script>
<!--<script src="../js/services/sharedService.js" type="text/javascript"></script>
<script src="../js/filters/filterChapitre.js" type="text/javascript"></script>
<script src="../js/filters/checkactif.js" type="text/javascript"></script>
<script src="../js/controllers/listIndic.js" type="text/javascript"></script>-->
<script>
    app.controller('PersonCtrl', function ($scope) {
            this.username = 'Todd Motto';
            this.friends = [{
                name: 'Andrew'
            }, {
                name: 'Will'
            }, {
                name: 'Mark'
            }, {
                name: 'Alice'
            }, {
                name: 'Todd'
            }];

            $scope.addFeed = function(feed) {
                console.log($scope.newFeed);
                if (feed.$valid) {
                    // Copy this feed instance and reset the URL in the form
                    var newFeed = angular.copy(feed);
                    $scope.feeds.push(newFeed);
                    $scope.fetchFeed(newFeed);
                    $scope.newFeed.url = '';
                }
            };
       }).controller("mainApp", function ($scope) {
        $scope.data = {};
    });

</script>
