<!-- Content Header (Page header) -->
<?php echo $this->titrepage_helper('Attribuer indicateurs', 'Attribution par utilisateur');  ?>


<!-- Main content -->
<section class="content" ng-app="attributeIndic">
    <div class="container-fluid" ng-init='userId=<?php echo $this->userId; ?>'></div>
    <h2><?php echo $user->getNom() . " " . $user->getPrenom() ?><small><?php echo $user->getPui()->getLibelle() ?></small></h2>
    <div class="row">
        <div class="col-xs-12" ng-controller="allIndics">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"><i class="fa fa-fw fa-sort-amount-desc"> </i>Liste de tous les indicateurs</h3>
                    <div class="box-tools">
                        <!--<h3>{{status}}</h3>-->
                        <div class="input-group">
                            <!--<input type="checkbox" name="actifYN" id="actifYN" ng-model="status"/>-->
                            <!--Value1: <input type="checkbox" ng-model="value1"> <br/>-->
                            <!--<input type="button" value="FilterYN" ng-model="value1" ng-click="dofilter()"/>
                            <tt>value1 = {{value1}}</tt><br/>-->
                            <!--<input type="text" placeholder="Search" style="width: 150px;" class="form-control input-sm pull-right" name="table_search">
                            <div class="input-group-btn">
                                <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                            </div>-->
                        </div>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding" style="height: 260px; overflow: auto;">
                    <table class="table header-fixed table-hover">
                        <tbody>
                        <tr>
                            <th class="col-md-1">ID</th>
                            <th>Chapitre</th>
                            <th class="col-md-1 hidden">Status</th>
                            <th>Titre</th>
                            <th class="col-md-1 text-center">Type</th>
                            <th>Tâche</th>
                            <th>Commentaire</th>
                            <th class="col-md-1">Chap id</th>
                        </tr>
                        <tr ng-class="(indic.actif) ? 'success' : 'is-grey-true'" ng-repeat="indic in indics | filter:{actif: true}">
                            <td>{{indic.indicateur.id}}</td>
                            <td>{{indic.indicateur.chapitre.titre}}</td>
                            <td class="vert-align hidden">
                                <span class="label" ng-class="(indic.actif) ? 'label-success' : 'label-danger'">{{indic.actif && "Activé" || "Désactivé"}}</span>
                            </td>
                            <td class="truncate">{{indic.indicateur.titre}}</td>
                            <td class="text-center">{{indic.type}}</td>
                            <td class="truncate">{{indic.indicateur.tache}}</td>
                            <td class="truncate">{{indic.indicateur.commentaire}}</td>
                            <td>chap. code: {{indic.indicateur.chapitre.code}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-xs-12" ng-controller="listIndic">
            <div class="box">
                <div class="box-header">
                    <div class="col-md-6 col-xs-12">
                        <h3 class="box-title">Changer les attributions</h3>
                    </div>
                    <div class="input-group col-md-6 col-xs-12" style="margin-top: 8px;">
                        <div class="form-group">
                            <label class="col-sm-2 col-xs-2 control-label" style="margin-top: 8px;" for="inputChapitre">Chapitre</label>
                            <div class="col-sm-10 col-xs-10">
                                <select placeholder="Email" class="form-control" id="chapitre" name="chapitresfilter"
                                        ng-options="chapitre.id as chapitre.title for chapitre in chapitres "
                                        ng-model="chapitre" ng-change="chapSelected()">
                                    <option style="display:none" value="">Choisir un chapitre</option>
                                </select>
                            </div>
                        </div>

                    </div>
                </div><!-- /.box-header -->

                <table class="table table-bordered example-animate-container">
                        <tbody>
                        <tr>
                            <th>ID</th>
                            <th>Titre</th>
                            <th class="text-center">Type</th>
                            <th>Tâche</th>
                            <th>Commentaire</th>
                            <th>Chap id</th>
                            <th>Status</th>
                        </tr>
                        <tr ng-class="(indic.actif) ? 'success' : 'is-grey-true'" ng-repeat="indic in indics |filter:customFilter() | orderBy: 'id' " ng-show="chapitre">
                            <td>{{indic.indicateur.id}}</td>
                            <td>{{indic.indicateur.titre}}</td>
                            <td class="text-center">{{indic.indicateur.type}}</td>
                            <td>{{indic.indicateur.tache}}</td>
                            <td>{{indic.indicateur.commentaire}}</td>
                            <td>chap. code: {{indic.indicateur.chapitre.code}}</td>
                            <td class="vert-align" style="text-align: center;"><a href="" ng-click="toggleActif(indic, $index)">{{indic.actif | checkactif}}</a></td>
                        </tr>
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
</section><!-- /.content -->

<script src="<?php echo $this->basePath("/") ?>./bower_components/angular/angular.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('./bower_components/angular-resource/angular-resource.js'); ?>"></script>
<script src="<?php echo $this->basePath('./bower_components/angular-route/angular-route.js'); ?>"></script>
<script src="<?php echo $this->basePath('./bower_components/angular-animate/angular-animate.js'); ?>"></script>
<!--<script type="text/javascript" src="../../bower_components/angular-growl-notifications/dist/angular-growl-notifications.js"></script>-->
<!--<script src="<?php $this->basePath(); ?>/bower_components/angular-bootstrap/ui-bootstrap.js" type="text/javascript"></script>-->

<script src="../../js/app.js" type="text/javascript"></script>
<script src="../../js/services/sharedService.js" type="text/javascript"></script>
<script src="../../js/services/IndicsUsers.js" type="text/javascript"></script>
<script src="../../js/filters/filterChapitre.js" type="text/javascript"></script>
<script src="../../js/filters/checkactif.js" type="text/javascript"></script>
<script src="../../js/controllers/allIndics.js" type="text/javascript"></script>
<script src="../../js/controllers/listIndic.js" type="text/javascript"></script>