<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css"/>

<?php
$this->headTitle()->append("au fil de l'eau");
?>
<br />
<!-- Content Header (Page header) -->
<?php echo $this->titrepage_helper('Attribution de score', 'au fil de l\'eau');  ?>

<div ng-app="scorefileau">
    <div class="container-fluid" ng-init='indicId=<?php echo $this->indic->getId(); ?>'></div>

    <div class="row" style="margin-left: 8px;">
        <h2><?php echo $indic->getTitre() ?><small><?php echo $indic->getTache() ?></small></h2>
    </div>
    <?php if($this->manyuser) { ?>
        <div class="alert alert-info" role="alert">
            <a href="#">Plusieurs utilisateurs sont attribués à cet indicateur</a>
        </div>
    <?php } ?>

    <div class="row" ng-controller="scoreFilEau">
        <div class="alert alert-success" role="alert" ng-show="messages != null" ng-cloak>{{messages}}</div>
        <div class="col-xs-12 col-md-10">
            <!-- FORM -->
            <!-- pass in the variable if our form is valid or invalid -->
            <form role="form" method="post" name="scoreForm" ng-submit="submitForm(scoreForm)" novalidate> <!-- novalidate prevents HTML5 validation since we will be validating ourselves -->
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"><i class="fa fa-fw fa-sort-amount-desc"> </i>Liste des saisies au fil de l'eau</h3>
                        <div class="box-tools">
                            <div class="input-group">
                            </div>
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body no-padding">
                        <table class="table table-hover table-striped">
                            <tbody>
                            <tr>
                                <th>Théme</th>
                                <th>Date</th>
                                <th>Durée</th>
                                <th colspan="3"></th>
                            </tr>
                            <tr ng-repeat="score in scoresData">
                                <td>
                                    <input name="id" type="hidden" ng-model="score.id" value="{{score.id}}"/>
                                    <div class="input-group">
                                        <input type="text" class="form-control" ng-model="score.theme" ng-required="true" value="theme"/>
                                    </div>
                                </td>
                                <td>
                                    <div class="input-group">
                                        <input type="text" class="form-control" datepicker-popup="{{format}}" ng-model="score.date"
                                               is-open="opened[$index]" ng-required="true" date-format="dd/mm/yyyy" date-type="string" date-disabled="disabled(date, mode)"
                                               close-text="Fermer" clear-text="Effacer" current-text="Aujourd'hui"/>
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-default" ng-click="open($event, $index)"><i
                                                    class="glyphicon glyphicon-calendar"></i></button>
                                        </span>
                                    </div>

                                </td>
                                <td ng-class="{ 'has-error' : scoreFieldForm.$invalid }">
                                    <ng-form name="scoreFieldForm">

                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-clock-o"></i>
                                            </div>
                                            <input type="text" name="valeur" ng-model="score.valeur" ng-pattern="/^\d+$/" class="form-control timepicker">
                                            <span class="input-group-addon bfh-number-btn inc">
                                                <span class="glyphicon glyphicon-chevron-up" ng-click="upScore($index, score.valeur)"></span>
                                            </span>
                                            <span class="input-group-addon bfh-number-btn dec">
                                                <span class="glyphicon glyphicon-chevron-down" ng-click="downScore($index, score.valeur)"></span>
                                            </span>
                                        </div>
                                    <p class="help-block" ng-show="scoreFieldForm.valeur.$invalid">La valeur doit être numerique.</p>
                                    <p class="help-block" ng-show="scoreFieldForm.valeur.$invalid">{{scoreForm.$invalid}}</p>
                                    </ng-form>
                                </td>
                                <td colspan="3">
                                    <div class="btn-toolbar pull-right">
                                        <div class="btn-group" ng-show="ishidden[$index]">
                                            <a class="btn btn-primary" href="" ng-click="addRow(score)" title="Ajouter un score">
                                                <span class="glyphicon glyphicon-plus"></span>
                                            </a>
                                        </div>
                                        <!--<div class="btn-group">
                                            <a class="btn btn-info" href="#">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>
                                        </div>
                                        <div class="btn-group">
                                            <form class="clearfix" accept-charset="UTF-8" action="#" method="POST">
                                                <button title="Löschen" class="btn btn-danger">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                            </form>
                                        </div>-->
                                    </div>
                                </td>

                            </tr>
                            </tbody>
                        </table>
                    </div><!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <button class="btn btn-primary" type="submit" ng-disabled="scoreForm.$invalid || scoresData.length === 0">Enregistrer</button>
                    </div><!-- /.box-footer -->
                </div><!-- /.box -->
            </form>
        </div>
    </div>

</div>

<script src="../bower_components/angular/angular.js" type="text/javascript"></script>
<script src="../bower_components/angular-resource/angular-resource.js"></script>
<script src="../bower_components/angular-animate/angular-animate.js"></script>
<script src="../bower_components/angular-bootstrap/ui-bootstrap.js"></script>
<script src="../bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.2.15/angular-locale_fr-fr.js"></script>
<script src="../js/app.js" type="text/javascript"></script>
<script src="../js/controllers/scoreFilEau.js" type="text/javascript"></script>
<script src="../js/services/Scores.js" type="text/javascript"></script>
