<li><a href="<?php echo $this->basepath(); ?>/indicateur">Indicateurs</a></li>
<li><a href="<?php echo $this->url("mesIndicateurs"); ?>">Mes Indicateurs</a></li>
<li>
	<a href="<?php echo $this->basepath(); ?>">Paramétrage</a>
	<ul>
		<li><a href="<?php echo $this->basepath(); ?>/etablissement/pui/edit">Information PUI</a></li>
		<li><a href="<?php echo $this->basepath(); ?>/utilisateur/utilisateur/list">Gestion des utilisateurs</a></li>
	</ul>
</li>
<li>
	<a href="<?php echo $this->basepath(); ?>">Reporting global</a>
	<ul>
		<li>
			<a href="<?php echo $this->basepath(); ?>">Outil de saisie<span class="opensubmenu">></span></a>
			<ul>
				<li><a href="<?php echo $this->basepath(); ?>/stats/stats/saisiecommercants">Suivi saisie par commerçant</a>
				<li><a href="<?php echo $this->basepath(); ?>/stats/stats/indicateurpui">Suivi saisie par PUI</a>
				<li><a href="<?php echo $this->basepath(); ?>/stats/stats/saisieannuelle">Suivi évolution sur + années</a>
			</ul>
		</li>
		<li>
			<a href="<?php echo $this->basepath(); ?>">Outil exploitation et de comparaison<span class="opensubmenu">></span></a>
			<ul>
				<li><a href="<?php echo $this->basepath(); ?>/stats/stats/comparatifindicateur">Comparatif saisies indicateur à une année</a>
				<li><a href="<?php echo $this->basepath(); ?>/stats/stats/comparatifannuel">Evolutions saisies  des 3 derrnières années d’un indicateur</a>
			</ul>
		</li>
	</ul>
</li>