<li><a href="<?php echo $this->basepath(); ?>/indicateur">Indicateurs</a></li>
<li><a href="<?php echo $this->url("mesIndicateurs"); ?>">Mes Indicateurs</a></li>
<li>
	<a href="<?php echo $this->basepath(); ?>">Reporting local</a>
	<ul>
		<li><a href="<?php echo $this->basepath(); ?>/stats/stats/indicateurcommercant">Suivi saisie par Pui</a></li>
		<li><a href="<?php echo $this->basepath(); ?>/stats/stats/saisieannuelle">Suivi évolution sur + années</a></li>
	</ul>
</li>