<li><a href="<?php echo $this->basepath(); ?>/indicateur">Indicateurs</a></li>
<li><a href="<?php echo $this->basepath(); ?>/etablissement/etablissement/list">Gérer les magasins</a></li>
<li><a href="<?php echo $this->basepath(); ?>/utilisateur/utilisateur/list">Gérer les utilisateurs</a></li>
<li>
	<a href="<?php echo $this->basepath(); ?>">Reporting global</a>
	<ul>
		<li><a href="<?php echo $this->basepath(); ?>/stats/stats/comparatifindicateur">Comparatif saisies indicateur à une année</a>
		<li><a href="<?php echo $this->basepath(); ?>/stats/stats/comparatifannuel">Evolutions saisies  des 3 derrnières années d’un indicateur</a>
	</ul>
</li>