<!-- Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-body">
            Installation successful! ZFB2 now is ready for action.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Let's go!</button>
        </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, cumque ea et, ipsum maiores modi molestiae non quam quis quisquam reiciendis reprehenderit sapiente voluptates. Amet molestias neque repellendus rerum temporibus.
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus consectetur consequuntur cum debitis dolores earum harum illum laboriosam, libero modi nam nulla odit pariatur repudiandae sequi sint soluta veritatis, voluptatem.

<script type="text/javascript">
//    $('#myModal').modal('show')
</script>